### ISSUE TITLE
mexFunction Arguments

### ISSUE THREAD

**Issue by Pandabear314** [nclack/mexrs#1]
I don't know if arguments to `mexFunction` were different in a this version of MATLAB however in the `plhs` and `prhs` should be swapped for current versions of MATLAB.

https://github.com/nclack/mexrs/blob/51a3ca1d0edd0ed6181f707c0fd0d7b219c05e60/hello/src/lib.rs#L17-L20

Should be:
```Rust
pub extern "C" fn mexFunction(nlhs: c_int,
                              plhs: *mut *mut mxArray,
                              nrhs: c_int,
                              prhs: *mut *mut mxArray) {
```

**Comment by nclack** [comment]
thanks you are 100% right.
